insert into seller (name, address, information) VALUES ('Petras', 'Vilniaus g. 10', 'Atsiliepiame į skambučius nuo 07-17:00. tel. 860000000');
insert into seller (name, address, information) VALUES ('Antanina', 'Kauno g. 10', 'Atsiliepiame į skambučius nuo 07-17:00. tel. 860000000');
insert into seller (name, address, information) VALUES ('Bogdan', 'Trakų g. 10', 'Atsiliepiame į skambučius nuo 07-17:00. tel. 860000000; Tik online');
insert into seller (name, address, information) VALUES ('Klimas', 'Šiaulių g. 10', 'Atsiliepiame į skambučius nuo 07-17:00. tel. 860000000');
insert into seller (name, address, information) VALUES ('UAB "Gėlės"', 'Panevėžio g. 10', 'Atsiliepiame į skambučius nuo 07-17:00. tel. 860000000; Galime priimti užsakymus gyvai');
insert into seller (name, address, information) VALUES ('Ramūnas', 'Vilniaus g. 10', 'Atsiliepiame į skambučius nuo 07-17:00. tel. 860000000');


INSERT INTO flower (name, price, photo, description, seller_id, days_to_expire) VALUES ('Frezija', 4.8, 'flowers/frezija.jfif', 'Vilkdalginių (Iridaceae) šeimos daugiamečių svogūninių augalų gentis. Kilusi iš Kapo regiono pievų (Pietų Afrikos Respublika), dabar auginamos visame pasaulyje kaip dekoratyvinės gėlės.', 1, 7);
INSERT INTO flower (name, price, photo, description, seller_id, days_to_expire) VALUES ('Gerbera', 1.68, 'flowers/gerbera.jfif', 'Astrinių (Asteraceae) šeimos augalų gentis. Natūraliai auga Pietų Amerikoje, Afrikoje, Madagaskare ir tropikinėje Azijoje.', 2, 4);
INSERT INTO flower (name, price, photo, description, seller_id, days_to_expire) VALUES ('Gvazdikas', 4.56, 'flowers/gvazdikas.jfif', 'Gvazdikinių (Caryophyllaceae) šeimos augalų gentis, kuriai priklauso žoliniai augalai bei krūmokšniai. Jų stiebai turi sustorėjusius bamblius. Lapai siauri, linijiški arba lancetiški. Žiedai sukrauti žiedynuose. Vaisius – vienalizdė dėžutė, kuri atsidaro 4 sąvaromis. Daugiausia daugiamečiai augalai, keletas rūšių vienmečių ir dvimečių.', 5, 5);
INSERT INTO flower (name, price, photo, description, seller_id, days_to_expire) VALUES ('Hiacintas', 10.68, 'flowers/hiacintas.jfif', 'Smidrinių (Asparagaceae) augalų gentis. Lietuvoje darželiuose auginama viena rūšis - rytinis hiacintas (Hyacinthus orientalis).', 1, 2);
INSERT INTO flower (name, price, photo, description, seller_id, days_to_expire) VALUES ('Kalija', 1.32, 'flowers/kalija.jfif', 'Lelijažiedžių (Liliidae) poklasio vilkdalginių (Iridaceae) šeimos augalų gentis. Augalai daugiamečiai su svogūniškais gumbais. Stiebas nešakotas, kalavijo formos lapais (lot. gladius ''toks romėniškas kalavijas, gladijus''). Žiedynas – vienašalė ar dvišalė varpa.', 6, 14);
INSERT INTO flower (name, price, photo, description, seller_id, days_to_expire) VALUES ('Kardelis', 9.24, 'flowers/kardelis.jfif', 'Aroninių (Araceae) šeimos Aroideae pošeimio augalų gentis. Paplitusi pietų Afrikoje iki Malavio šiaurinėje dalyje.', 1, 4);
INSERT INTO flower (name, price, photo, description, seller_id, days_to_expire) VALUES ('Lelija', 2.88, 'flowers/lelija.jfif', 'Lelijinių (Liliaceae) šeimos augalų gentis, kuriai priklauso daugiametės svogūninės žolės, turinčios kiaušiniškus svogūnus ir stačius lapuotus stiebus. Lapai dažniausiai siauri, bekočiai. Žiedai įvairių spalvų ir dydžio, vienų rūšių nusvirę, kitų statūs, sukrauti kekėse ar išaugę pavieniui. Apyžiedžio lapeliuose yra nektarinės. Vaisius – dėžutė.', 3, 5);
INSERT INTO flower (name, price, photo, description, seller_id, days_to_expire) VALUES ('Narcizas', 8.88, 'flowers/narcizas.jfif', 'Amarilinių (Amaryllidaceae) šeimos augalų gentis. Genties pavadinimas kildinamas iš graikų k. žodžio narkao – svaiginu; žiedai turi stiprų svaiginantį kvapą. Daugiamečiai svogūniniai augalai. Stiebas ilgas, belapis, su plėvine makštimi pamate ir linijiškais pamatiniais lapais. Žiedai gana stambūs, pavieniai arba susitelkę po kelis. Sėklos juodos, rutuliškos arba kampuotos.', 2, 5);
INSERT INTO flower (name, price, photo, description, seller_id, days_to_expire) VALUES ('Orchidėja', 3.48, 'flowers/orchideja.jfif', 'Gegužraibinių (Orchidaceae) šeimos augalų gentis, kuriai priklauso dauguma epifitinių ir kelios litofitinės orchidėjos. Gentį aprašė 1826 m. Bliumė (Blume). Pavadinimas iš gr. phalaina – drugys ir opsis – panašus; kai kurių', 2, 8);
INSERT INTO flower (name, price, photo, description, seller_id, days_to_expire) VALUES ('Rožė', 10.08, 'flowers/roze.jfif', 'Erškėčių (Rosa) genties dekoratyvinis augalas. Rožės dažnai laikomos dieviškumo, tobulo grožio, o raudonosios – meilės simboliu. Vakarų pasaulyje rožė laikoma kilmingiausia gėle. Jos atskirai ar puokštėse dovanojamos įvairiomis progomis.', 1, 5);
INSERT INTO flower (name, price, photo, description, seller_id, days_to_expire) VALUES ('Tulpė', 6.6, 'flowers/tulpe.jfif', 'Lelijinių augalų (Liliaceae) gentis. Joms būdingi dideli šešių žiedlapių žiedai. Iš viso yra apie 100 rūšių, Lietuvoje auginamos tik kaip dekoratyviniai augalai, laukinės neauga. Tulpės kilusios iš pietų Europos, Šiaurės Afrikos ir Azijos (nuo Anatolijos ir Irano iki Kinijos ir Japonijos). Daugiausia genties rūšių Pamyro ir Hindukušo kalnuose bei Kazachstano stepėse.', 5, 5);